bash mirror-gh.sh angular / angular.js
bash mirror-gh.sh yui / yui3
bash mirror-gh.sh mozilla-b2g / gaia
bash mirror-gh.sh adobe / brackets
bash mirror-gh.sh saltstack / salt
bash mirror-gh.sh rails / rails
bash mirror-gh.sh html5rocks / www.html5rocks.com
bash mirror-gh.sh fog / fog
bash mirror-gh.sh elasticsearch / elasticsearch
bash mirror-gh.sh scala / scala
bash mirror-gh.sh JuliaLang / julia
bash mirror-gh.sh lift / framework
bash mirror-gh.sh travis-ci / travis-ci
bash mirror-gh.sh bundler / bundler
bash mirror-gh.sh edx / edx-platform
bash mirror-gh.sh TryGhost / Ghost
bash mirror-gh.sh docker / docker
bash mirror-gh.sh rust-lang / rust
bash mirror-gh.sh particular / NServiceBus
bash mirror-gh.sh Khan / khan-exercises
